Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }

    [Required(ErrorMessage = "Machine name can't be left empty")]
    public string MachineName { get; set; }
    [Required(ErrorMessage = "Machine number can't be left empty")]
    public int MachineNumber { get; set; }

    public List<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers
                          .OrderBy(engineer => engineer.EngineerName)
                          .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }


    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
          ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
          return View(engineer);
      }
      else
      {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Engineer foundEngineer = _db.Engineers
                                .Include(engineer => engineer.JoinEntities)
                                .ThenInclude(join => join.Machine)
                                .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(foundEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      if(!ModelState.IsValid)
      {
        return View(engineer);
      }
      else
      {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId});
      }
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

        public ActionResult AddMachine (int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine (Engineer engineer, int machineId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
#nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    [HttpPost]
    public ActionResult DeleteJoin (int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines
                          .OrderBy(machine => machine.MachineName)
                          .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if(!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
      #nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
                              .Include(machine => machine.JoinEntities)
                              .ThenInclude(join => join.Engineer)
                              .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      if(!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
        _db.Machines.Update(machine);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = machine.MachineId });
      }
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="card" style="width: 18rem;" id="views">
  <h2>Add Engineer</h2>

  <h3>Add an engineer to this machine: @Html.DisplayFor(model => model.MachineName)</h3>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    <div class="form-group">
      @Html.Label("Select an engineer:")
      @Html.DropDownList("EngineerId")
    </div>

    <input type="submit" value="Add Engineer" class="btn btn-primary" />
  }

    @Html.ActionLink("Back to List", "Index")
</div>

Factory/Views/Machines/AddStudent.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

@* <h2>Add student</h2>

<h3>Add a student to this course: @Html.DisplayFor(model => model.CourseName)</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  <div class="form-group">
    @Html.Label("Select a student")
    @Html.DropDownList("StudentId")
  </div>

  <input type="submit" value="Add Student" class="btn btn-primary" />
}

  @Html.ActionLink("Back to List", "Index") *@

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="card" style="width: 18rem;" id="views">
  <h4>Add a new machine</h4>
  <hr />

  <p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

  @using (Html.BeginForm())
  {
    <p>Machine Name: @Html.TextBoxFor(model => model.MachineName, new { required = "required" })</p>
    
    <p>Machine Number: @Html.TextBoxFor(model => model.MachineNumber, new { @type = "number", required = "required" })</p>
      
    <input type="submit" value="Add new machine"/>
  }
  <br>
  <p>@Html.ActionLink("Show all machines", "Index")</p>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="card" style="width: 18rem;" id="views">
  <h2>Are you sure you want to delete this machine?</h2>

  @Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
  @Html.ActionLink("Back to List", "Index")
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;
@using Factory.Models;

<div class="card" style="width: 18rem;" id="views">
  <h2>Machine Details</h2>
  <hr />
  <h3>@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h3>
  <h3>@Html.DisplayNameFor(model => model.MachineNumber): @Html.DisplayFor(model => model.MachineNumber)</h3>

  @if (Model.JoinEntities.Count == 0)
  {
    <p>This machine does not have any engineers assigned yet</p>
  }
  else
  {
    <h4>Engineers assigned to this machine:</h4>
    <ul>
    @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li>@join.Engineer.EngineerName</li>
      @using (Html.BeginForm("DeleteJoin", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Remove engineer from this machine" />
      }
    }
    </ul>
  }

  <p>@Html.ActionLink("Back to machines", "Index")</p>
  <p>@Html.ActionLink("Assign an engineer to this machine", "AddEngineer", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Edit machine", "Edit", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Delete machine", "Delete", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Add new engineer", "Create", "Engineers")</p>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="card" style="width: 18rem;" id="views">
  <h4>Edit this machine: @Html.DisplayFor(model => model.MachineName)</h4>

  <p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

  <p>@Html.ValidationMessageFor(model => model.MachineNumber, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)
    <p>Machine Name: @Html.EditorFor(model => model.MachineName)</p>
    <p>Machine Number:  @Html.EditorFor(model => model.MachineNumber)</p>
      
    <input type="submit" value="Save" />
  }

  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="card" style="width: 18rem;" id="views">
  <h1>Machines</h1>

  @if (@Model.Count == 0)
  {
    <h3>No machines have been added yet!</h3>
  } 

  <ul>
    @foreach(Machine machine in Model)
    {
      <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
    }
  </ul>

  <p>@Html.ActionLink("Add new machine", "Create")</p>
  <p>@Html.ActionLink("Add new engineer", "Create", "Engineers")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>